# Generated by Django 5.0 on 2023-12-28 13:51

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Botique',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=190, null=True)),
                ('phone_nember', models.CharField(max_length=190, null=True)),
                ('location', models.CharField(max_length=190, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Client',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=190, null=True)),
                ('Email', models.CharField(max_length=190, null=True)),
                ('phone', models.CharField(max_length=190, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Tag',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=190, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Demand',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('pris', models.FloatField(null=True)),
                ('data_created', models.DateTimeField(auto_now_add=True, null=True)),
                ('status', models.CharField(choices=[('resu', 'resu'), ('in progress', 'in progress'), ('perd', 'perd')], max_length=190, null=True)),
                ('botique', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='Login01.botique')),
                ('client', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='Login01.client')),
                ('tags', models.ManyToManyField(to='Login01.tag')),
            ],
        ),
    ]
